# Changes here will be overwritten by Copier
_commit: 1.3.0
_src_path: gh:AdrienCos/seedlings
author_email: adrien@cosson.io
author_name: Adrien Cosson
author_username: AdrienCos
enable_release_ci: true
package_name: adriencos_sapling
project_name: Sapling
repository_url: https://github.com/AdrienCos/sapling
short_description: A Python project based on the Seedlings template
