# .gitlab-ci.yml

stages:
  - pr-ci

pr-ci:
  services:
    - name: "docker:dind"
      alias: "docker"
  variables:
    DOCKER_HOST: tcp://docker:2375
    FORCE_COLOR: 1
    EARTHLY_EXEC_CMD: "/bin/sh"
  image: earthly/earthly:v0.8.13

  # before_script:
  #   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  stage: pr-ci
  script:
    - docker info
    - earthly --strict +all --tag=${CI_COMMIT_SHORT_SHA}
