---
name: "Common"
description: "Common steps for all Actions"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - run: pip install pdm
      shell: bash
    - run: pdm sync
      shell: bash
