---
name: Create a Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions: # Required to create a release
  contents: write

jobs:
  build-and-push:
    name: Build the artifacts and push the Docker image
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: AdrienCos
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run the +docker step in Earthly
        run: earthly --strict --push +docker --registry_prefix="ghcr.io/" --tag=${GITHUB_REF_NAME}

  create-gh-release:
    name: Create and publish a tagged release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - name: Run the +create-gh-release step in Earthly
        run: earthly --push --strict --secret GH_TOKEN=${{ secrets.GITHUB_TOKEN }} +create-gh-release --tag=${GITHUB_REF_NAME}
