---
name: Renovate

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - "master"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.4
        with:
          configurationFile: renovate.gha.json
          token: ${{ secrets.RENOVATE_TOKEN }}
